#!/usr/bin/env bash
# Generates dist/studio_api_config.php from repository secrets.
#
# The config file is gitignored and was previously uploaded by hand, which is
# easy to get wrong or lose. Generating it during the deploy keeps the secrets
# in GitHub and makes the deployed file reproducible.
#
# Missing values are skipped rather than written as empty strings, so a partial
# secret set still produces a valid file.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DIST_DIR="$ROOT_DIR/dist"
TARGET="$DIST_DIR/studio_api_config.php"

if [ ! -d "$DIST_DIR" ]; then
  echo "dist/ does not exist; run the build first." >&2
  exit 1
fi

php_export() {
  # Escapes a value for a single-quoted PHP string.
  printf "%s" "$1" | sed "s/'/\\\\'/g"
}

ADMIN_PASSWORD="${STUDIO_ADMIN_PASSWORD:-}"
SYNC_TOKEN="${STUDIO_API_SYNC_TOKEN:-}"
WRITE_TOKEN="${STUDIO_API_WRITE_TOKEN:-}"
GOOGLE_CLIENT_ID="${GOOGLE_CLIENT_ID:-}"
GOOGLE_CLIENT_SECRET="${GOOGLE_CLIENT_SECRET:-}"

missing=()
[ -z "$SYNC_TOKEN" ] && missing+=("STUDIO_API_SYNC_TOKEN")
[ -z "$GOOGLE_CLIENT_ID" ] && missing+=("GOOGLE_CLIENT_ID")
[ -z "$GOOGLE_CLIENT_SECRET" ] && missing+=("GOOGLE_CLIENT_SECRET")

{
  echo "<?php"
  echo "// Generated by .github/scripts/write-api-config.sh during deploy."
  echo "// Do not edit on the server: the next deploy overwrites this file."
  echo "// Change the values in GitHub > Settings > Secrets and variables > Actions."
  echo
  echo "\$admin_password = '$(php_export "$ADMIN_PASSWORD")';"
  echo "\$sync_token = '$(php_export "$SYNC_TOKEN")';"
  echo "\$write_token = '$(php_export "$WRITE_TOKEN")';"
  echo
  echo "// Personal-app default: list create/edit/delete needs no extra token."
  echo "\$require_list_write_auth = false;"
  echo
  echo "\$google_client_id = '$(php_export "$GOOGLE_CLIENT_ID")';"
  echo "\$google_client_secret = '$(php_export "$GOOGLE_CLIENT_SECRET")';"
  echo
  echo "// Pre-accounts clients may act as the owner by presenting a secret above."
  echo "\$allow_legacy_token_owner_access = true;"
} > "$TARGET"

# Refuse to ship a file PHP cannot parse.
php -l "$TARGET" > /dev/null

# Prove the credentials were actually written, without printing them.
php -r '
$f = $argv[1];
$admin_password = "";
$sync_token = "";
$write_token = "";
$google_client_id = "";
$google_client_secret = "";
require $f;
printf("  admin_password: %s\n", trim((string) $admin_password) !== "" ? "set" : "not set");
printf("  sync_token    : %s\n", trim((string) $sync_token) !== "" ? "set" : "NOT SET (runtime mirror will be skipped)");
printf("  google id     : %s\n", trim((string) $google_client_id) !== "" ? "set (" . strlen(trim((string) $google_client_id)) . " chars)" : "NOT SET (Google button hidden)");
printf("  google secret : %s\n", trim((string) $google_client_secret) !== "" ? "set (" . strlen(trim((string) $google_client_secret)) . " chars)" : "NOT SET (Google button hidden)");
' "$TARGET"

if [ ${#missing[@]} -gt 0 ]; then
  echo "Warning: missing secrets: ${missing[*]}" >&2
  echo "Add them under Settings > Secrets and variables > Actions to enable those features." >&2
fi

echo "Wrote $TARGET"
